//shows exact error

class trycatchfinally3 {

        public static void main (String[] args) {

            try{
                methodA();

                System.out.println("Exit main()");

            }
            catch(ArithmeticException ex)
            {
                System.out.println("ArithmeticException caught ...");

                ex.printStackTrace(); //it shows stack of error in order of occurrence
            }
        }

        static void methodA()
        {
            System.out.println("Enter methodA()");
            try{
                int a = 5, b = 0;

                int c = a / b;

                System.out.println(c);
            }
            finally{

                System.out.println("finally in methodA()");
            }
            System.out.println("Exit methodA()");
        }
}

